apiVersion: v2
name: my-app
description: "Aplicación modular con frontend, backend y base de datos usando subcharts"
type: application
version: 0.1.0
appVersion: "1.0.0"

# Subcharts locales
dependencies:
  - name: frontend
    version: 0.1.0
    repository: "file://charts/frontend"
  - name: backend
    version: 0.1.0
    repository: "file://charts/backend"
  - name: database
    version: 0.1.0
    repository: "file://charts/database"
