# Valores por defecto para los subcharts
frontend:
  image:
    repository: nginx
    tag: "1.27-alpine"
    pullPolicy: IfNotPresent
  replicas: 1
  service:
    type: ClusterIP
    port: 80
  resources: {}
  env: []  # p.ej., [{name: BACKEND_URL, value: "http://backend:5000"}]

backend:
  image:
    repository: ghcr.io/example/backend
    tag: "1.0.0"
    pullPolicy: IfNotPresent
  replicas: 1
  service:
    type: ClusterIP
    port: 5000
  resources: {}
  env:
    - name: MYSQL_HOST
      value: database
    - name: MYSQL_DATABASE
      value: appdb
    - name: MYSQL_USER
      value: appuser
    - name: MYSQL_PASSWORD
      value: appr0cks

database:
  image:
    repository: mysql
    tag: "8.0"
    pullPolicy: IfNotPresent
  replicas: 1
  service:
    type: ClusterIP
    port: 3306
  persistence:
    enabled: true
    accessModes: ["ReadWriteOnce"]
    size: 5Gi
    storageClassName: ""  # deja vacío para usar la default, o pon tu StorageClass
    existingClaim: ""     # si quieres usar un PVC existente
  mysqlRootPassword: "rootpass123"
  mysqlDatabase: "appdb"
  mysqlUser: "appuser"
  mysqlPassword: "appr0cks"
  resources: {}
