frontend:
  image:
    repository: nginx
    tag: "1.27-alpine"
  replicas: 3
  service:
    type: LoadBalancer
    port: 80
  resources:
    limits:
      cpu: "200m"
      memory: "128Mi"
    requests:
      cpu: "100m"
      memory: "64Mi"
  env:
    - name: BACKEND_URL
      value: "http://backend:5000"

backend:
  image:
    repository: ghcr.io/example/backend
    tag: "1.0.0"
  replicas: 3
  service:
    type: ClusterIP
    port: 5000
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"

database:
  image:
    repository: mysql
    tag: "8.0"
  persistence:
    size: 20Gi
  resources:
    limits:
      cpu: "500m"
      memory: "1Gi"
    requests:
      cpu: "200m"
      memory: "512Mi"
