apiVersion: v1
kind: Service
metadata:
  name: {{ include "database.fullname" . | default (printf "%s-database" .Release.Name) }}
  labels:
    app.kubernetes.io/name: database
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: database
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: mysql
      port: {{ .Values.service.port }}
      targetPort: 3306
